import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import Layout from "@/components/layouts/Layout";

import "../globals.scss";
import Providers from "@/config/providers/Providers";

const geistSans = Roboto({
  variable: "--font-geist-sans",
  weight: "500",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <Providers>
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
