version: '3.8'

services:
    web-app:
        build:
            context: .
            dockerfile: docker/Dockerfile.server
        ports:
          - "8000:8000"
        volumes:
          - ".:/web"
        environment:
            - DB_HOST=db-54321
            - DB_NAME=tedis
            - DB_USER=dbuser
            - DB_PASS=pass
        command: >
            sh /web/scripts/start.sh

        depends_on:
            - db-54321

    # web-app-client:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile.client
    #     ports:
    #       - "3000:3000"
    #     volumes:
    #       - ".:/app"
    #     command: >
    #         sh -c "npm run dev"
    #     depends_on:
    #         - web-app

    db-54321:
        container_name: db-54321-1
        image: postgres:17-alpine
        environment:
            - POSTGRES_DB=tedis
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=pass
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    redis:
        image: redis:7.0.5-alpine
        container_name: redis-container
        hostname: redis
        volumes:
            - redis_data:/var/lib/redis/data/
        ports:
            - 6379:6379
        restart: always

    worker:
        build:
            context: .
            dockerfile: docker/Dockerfile.server
        hostname: worker
        entrypoint: celery
        command: -A server worker --pool=solo -l info
        volumes:
          - ".:/web"
        #В docker-compose, директива links используется для связи контейнеров, чтобы они могли обращаться друг к другу по именам хостов. Когда контейнеры запускаются с использованием docker-compose, links позволяет одному контейнеру подключаться к другому с использованием DNS-имени контейнера, указанного в links. Это было полезно в старых версиях Docker, но в последних версиях рекомендуется использовать сеть (network) вместо links.
        links:
          - redis
        depends_on:
            - redis
            - db-54321
        environment:
            - DB_HOST=db-54321
            - DB_NAME=tedis
            - DB_USER=dbuser
            - DB_PASS=pass

    flower:
        build:
            context: .
            dockerfile: docker/Dockerfile.server
        hostname: flower
        entrypoint: celery
        command: -A server flower
        volumes:
          - ".:/web"
        links:
          - redis
        depends_on:
            - redis
        ports:
          - "5555:5555"

volumes:
    postgres_data:
    redis_data:
