version: '3.8'

services:
    web-app:
        build:
            context: .
            dockerfile: docker/Dockerfile.server
        ports:
          - "8000:8000"
        volumes:
          - ".:/web"
        environment:
            - DB_HOST=db-54321
            - DB_NAME=tedis
            - DB_USER=dbuser
            - DB_PASS=pass
        command: >
            sh /web/scripts/start.sh

        depends_on:
            - db-54321
    # web-app-client:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile.client
    #     ports:
    #       - "3000:3000"
    #     volumes:
    #       - ".:/app"
    #     command: >
    #         sh -c "npm run dev"
    #     depends_on:
    #         - web-app

    db-54321:
        container_name: db-54321-1
        image: postgres:17-alpine
        environment:
            - POSTGRES_DB=tedis
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=pass
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
