FROM node:18-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* /app/

RUN npm install

COPY . .

ENV MODE production

RUN mkdir .next

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
