# Generated by Django 5.1.4 on 2025-02-02 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='house_number',
            field=models.PositiveIntegerField(default=0, help_text='Enter a positive integer for the house number', validators=[django.core.validators.MinValueValidator(1)], verbose_name='house number'),
        ),
    ]
