# Generated by Django 5.1.4 on 2025-02-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_customers_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='bio',
            field=models.TextField(max_length=400, verbose_name='user description'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(max_length=45, verbose_name='zip code'),
        ),
    ]
