# Generated by Django 5.1.4 on 2025-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_product_banner_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='street',
            field=models.CharField(blank=True, max_length=45, verbose_name='user street'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(blank=True, max_length=45, verbose_name='zip code'),
        ),
    ]
