# Generated by Django 5.1.4 on 2025-04-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_customers_first_name_alter_customers_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='street',
            field=models.CharField(max_length=45, verbose_name='user street'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(max_length=45, verbose_name='zip code'),
        ),
    ]
