# Generated by Django 5.1.4 on 2025-02-07 12:52

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models

import random


def create_test_data(apps, schema_editor):
    Category = apps.get_model('server', 'Category')
    Product = apps.get_model('server', 'Product')
    User = get_user_model()

    # Проверяем, существуют ли уже категории
    if Category.objects.exists():
        print("Категории уже существуют. Пропускаем создание.")
        return

    # Получаем первого пользователя (или создаем, если его нет)
    user = User.objects.first()
    if not user:
        user = User.objects.create(username='testuser', email='test@example.com')

    # Создаем три категории
    categories = []
    for i in range(1, 4):
        category, created = Category.objects.get_or_create(
            title=f'Категория {i}',
            metaTitle=f'Категория {i} Meta',
            slug=f'category-{i}',
            parent=None
        )
        categories.append(category)

    # Проверяем, существуют ли уже продукты
    if Product.objects.exists():
        print("Продукты уже существуют. Пропускаем создание.")
        return

    # Создаем 100 продуктов
    for i in range(1, 101):
        Product.objects.create(
            title=f'Продукт {i}',
            metaTitle=f'Продукт {i} Meta',
            slug=f'product-{i}',
            summary=f'Описание продукта {i}',
            accessibility=random.choice(['available', 'out_of_stock', 'coming_soon', 'pre_order']),
            condition=random.choice(['new', 'used', 'refurbished', 'damaged']),
            warehouse=random.choice(['reserved', 'in_warehouse', 'out_for_delivery']),
            promotional=random.choice(['on_sale', 'limited_offer', 'flash_sale', 'black_friday']),
            checks='approved',
            category=random.choice(categories),
            user=user
        )


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_customers_role_alter_customers_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('metaTitle', models.CharField(max_length=100, verbose_name='meta title')),
                ('slug', models.SlugField(blank=True, help_text='Unique tag ID for URL', unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.category', verbose_name='parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('metaTitle', models.CharField(max_length=100, verbose_name='meta title')),
                ('slug', models.SlugField(blank=True, help_text='Unique tag ID for URL', unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=30, null=True, verbose_name='product summary')),
                ('accessibility', models.CharField(choices=[('available', 'Доступен'), ('out_of_stock', 'Нет в наличии'), ('coming_soon', 'Скоро в продаже'), ('pre_order', 'Предзаказ')], default='coming_soon', max_length=30, verbose_name='product accessibility')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У'), ('refurbished', 'Восстановленный'), ('damaged', 'Поврежден')], default='new', max_length=30, verbose_name='product condition')),
                ('warehouse', models.CharField(choices=[('reserved', 'Зарезервирован'), ('in_warehouse', 'На складе'), ('out_for_delivery', 'Отправлен на доставку')], default='in_warehouse', max_length=30, verbose_name='product warehouse')),
                ('promotional', models.CharField(choices=[('on_sale', 'Акция'), ('limited_offer', 'Ограниченное предложение'), ('flash_sale', 'Молниеносная распродажа'), ('black_friday', 'Черная пятница')], default='on_sale', max_length=30, verbose_name='product promotional')),
                ('checks', models.CharField(choices=[('under_review', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='under_review', max_length=30, verbose_name='product checks')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.category', verbose_name='product category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='product user')),
            ],

            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),

        migrations.RunPython(create_test_data)
    ]
