# Generated by Django 5.1.4 on 2025-02-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
