# Generated by Django 5.1.4 on 2025-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_product_discount_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique tag ID for URL', max_length=150, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('subscriber', 'Подписчик'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique tag ID for URL', max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
