# Generated by Django 5.1.4 on 2025-03-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_category_icno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icno',
            new_name='icon',
        ),
    ]
