# Generated by Django 5.1.4 on 2025-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_rename_icno_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Popular Search',
                'verbose_name_plural': 'Popular Searches',
            },
        ),
    ]
