# Generated by Django 5.1.4 on 2025-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_popularsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='HelpCircle', max_length=20),
        ),
    ]
