# Generated by Django 5.1.4 on 2025-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10, verbose_name='product price discount'),
        ),
    ]
