# Generated by Django 5.1.4 on 2025-03-21 14:11

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_product_price_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateCodeConfirmationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('code', models.CharField(help_text='A 6-digit confirmation code', max_length=6, verbose_name='Confirmation Code')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Uuid CODE')),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2025, 3, 21, 14, 21, 26, 63707, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Generate Code',
                'verbose_name_plural': 'Generate Codes',
            },
        ),
    ]
