# Generated by Django 5.1.4 on 2025-03-21 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_generatecodeconfirmationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 15, 7, 37, 931684, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
