# Generated by Django 5.1.4 on 2025-03-22 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_generatecodeconfirmationemail_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 7, 53, 26, 442341, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
