# Generated by Django 5.1.4 on 2025-03-23 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_generatecodeconfirmationemail_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodeconfirmationemail',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 16, 46, 5, 927904, tzinfo=datetime.timezone.utc), verbose_name='Expiry Time'),
        ),
    ]
