# Generated by Django 5.1.4 on 2025-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_productimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('metaTitle', models.CharField(max_length=100, verbose_name='meta title')),
                ('slug', models.SlugField(blank=True, help_text='Unique tag ID for URL', max_length=150, unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title', 'metaTitle'], name='server_prod_title_b615f7_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['title', 'metaTitle'], name='server_bann_title_14a198_idx'),
        ),
    ]
