# Generated by Django 5.1.4 on 2025-03-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_banner_product_server_prod_title_b615f7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.banner', verbose_name='product banner'),
        ),
    ]
