# Generated by Django 5.1.4 on 2025-03-29 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_product_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
